<a href="https://colab.research.google.com/github/FrancescoMusi/Laboratory-of-machine-learning-and-advanced-computing-for-physics/blob/main/7_Introduction_to_pythorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Basic use of PyTorch

*Adapted from `pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html`*.

Tensors are a specialized data structure that are very similar to `numpy` (multidimensional) arrays.
In PyTorch, we use tensors to encode the inputs and outputs of a model, as well as the model’s parameters.

In contrast to `numpy` arrays, `torch` tensors can run on GPUs or other hardware accelerators.

Tensors are also optimized for automatic differentiation.

In [ ]:
import torch
import numpy as np

## Initializing a Tensor

In [ ]:
# directly from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [ ]:
# from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [ ]:
x_np

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_data

tensor([[1, 2],
        [3, 4]])

In [ ]:
x_np.numpy()

array([[1, 2],
       [3, 4]])

In [ ]:
# from another torch tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



In [ ]:
# overriding the datatype of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Random Tensor: 
 tensor([[0.0559, 0.7630],
        [0.4761, 0.2633]]) 



In [ ]:
# Set seed for reproducibility
torch.manual_seed(42)

shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


# Some Tensor Attributes

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


# Operations on Tensors

In [ ]:
torch.cuda.is_available()

True

In [ ]:
# Move our tensor to the GPU, since it is available (faster calculations)
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

print(tensor.device)

In [ ]:
tensor = torch.ones(3,4)
tensor, tensor[0]

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([1., 1., 1., 1.]))

In [ ]:
tensor.device

device(type='cpu')

In [ ]:
y = tensor @ tensor.T

In [ ]:
print(y)

tensor([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]])


In [ ]:
somma = tensor.sum()

In [ ]:
somma

tensor(12.)

In [ ]:
somma.item()

12.0

# Autograd

In [ ]:
a = torch.tensor([2.], requires_grad=True)
b = torch.tensor([6.], requires_grad=True)

In [ ]:
# Define a new tensor Q that is a function of a and b
Q =  3 * a**3 - b**2

In [ ]:
Q

tensor([-12.], grad_fn=<SubBackward0>)

In [ ]:
# Compute the derivatives of Q w.r.t. a and b, computed at the values that the latter have
Q.backward()

In [ ]:
a.grad

tensor([36.])

In [ ]:
b.grad

tensor([-12.])

In [ ]:
# Caveat: accumulation and not substitution
Q

tensor([-12.], grad_fn=<SubBackward0>)

In [ ]:
Q = 3 * a**3 - b**2
Q.backward()

In [ ]:
a.grad

tensor([72.])

In [ ]:
a.grad.zero_()

tensor([0.])

In [ ]:
Q = 3 * a**3 - b**2
Q.backward()

In [ ]:
a.grad

tensor([36.])

# Exercises


1.   Try this for tesnors that are not just one-element
2.   Try with complicated functions and check the result analytically with Wolfram Alpha
3.    Try to work on cuda device, rather than CPU
4.    Use the recipe in [here](https://docs.pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html) to build a NN and fit a simple function.

